# Generated by Django 5.1.3 on 2024-12-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores_profesionales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='equipos/'),
        ),
    ]
